#!/bin/bash

yourdomain="$1"


upgradeSys_installPack() {
	apt update
	apt upgrade -y
	apt install --no-install-recommends -y mysql-server nginx php php-fpm php-mysql
}

nginx_default() {
	printf "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_tokens off;
	default_type \"text/html\";
	return 200 'This is default http';
	}
server {
	listen 443 ssl default_server;
	listen [::]:443 ssl default_server;
	ssl_certificate default.crt;
	ssl_certificate_key default.key;
	server_tokens off;
	default_type \"text/html\";
	return 200 'This is default https';
	}" > /etc/nginx/sites-enabled/default

}

certkeygen() {
	cd /etc/nginx/
	openssl req -x509 -out default.crt -keyout default.key \
	-newkey rsa:2048 -nodes -sha256 -subj '/CN=localhost' -extensions EXT -config <(printf "
	[dn]
	CN=localhost
	[req]
	distinguished_name = dn
	[EXT]
	subjectAltName=DNS:localhost
	keyUsage=digitalSignature
	extendedKeyUsage=serverAuth")
}
 
setup_default_site() {
	nginx_default
	certkeygen
	nginx -s reload
}

nginx_configure() {
	mkdir /var/www/"$yourdomain"  /var/www/"$yourdomain"/html
	printf "
server {
        listen 80;
        listen [::]:80;
        root /var/www/$yourdomain/html;
        index index.html index.htm index.nginx-debian.html;
        server_name $yourdomain www.$yourdomain;
        location / {
                try_files \$uri \$uri/ =404;
        }
}" > /etc/nginx/sites-enabled/"$yourdomain"

	nginx -s reload
}

upgradeSys_installPack
setup_default_site
nginx_configure
